version: "3.8"

services:
  filRouge:
    image: hajarhamim/fil-rouge-conseil:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
    networks:
      - myconseil-network

  mysqldb:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: conseilhair
      MYSQL_ALLOW_EMPTY_PASSWORD: jujuRO55
    ports:
      - "3307:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - myconseil-network

volumes:
  mysqldb:

networks:
  myconseil-network:
    driver: bridge
