// pipeline {
//     agent any
//
//     tools {
//         maven 'mvn'
//     }
//
//     environment {docker-credentials-id
//         SONARQUBE_SERVER = 'SonarQubeServer'
//         DOCKER_HUB_REPO = 'hajarhamim/fil-rouge-conseil'
//         SONAR_TOKEN = credentials('CONSEIL')
//         DOCKER_COMPOSE_FILE = 'docker-compose.yml'
//         DOCKER_CREDENTIALS_ID = ''
//     }
//
//     stages {
//         stage('Checkout') {
//             steps {
//                 git branch: 'main', url: 'https://github.com/Hamim-Hajar/Fil-Rouge-Conseil-Beauty.git'
//             }
//         }
//
//         stage('Build and Unit Tests') {
//             steps {
//                 dir('conseil') {
//                     bat "mvn clean install"
//                     bat "mvn test"
//                 }
//             }
//         }
//
//         stage('SonarQube Analysis') {
//             steps {
//                 withSonarQubeEnv('SonarQubeServer') {
//                    bat "mvn sonar:sonar -Dsonar.token=${SONAR_TOKEN}"
//                 }
//             }
//         }
//
//         stage('Quality Gate Check') {
//             steps {
//                 timeout(time: 5, unit: 'MINUTES') {
//                     waitForQualityGate abortPipeline: true
//                 }
//             }
//         }
//
//         pipeline {
//             agent any
//
//             stages {
//                 stage('Build Docker Image for Backend') {
//                     steps {
//                         script {
//                             dir('conseil') {
//                                 bat 'docker build -t fil-rouge-conseil .'
//                             }
//                         }
//                     }
//                 }
//
//                 stage('Tag and Push Docker Image to Docker Hub') {
//                     steps {
//                         script {
//                             docker.withRegistry("https://index.docker.io/v1/", 'docker-credentials-id') {
//                                 def imageName = "${DOCKER_HUB_REPO}/fil-rouge-conseil"
//                                 bat """
//                                     docker tag il-rouge-conseil latest ${imageName}:latest
//                                     docker push ${imageName}:latest
//                                 """
//                             }
//                         }
//                     }
//                 }
//             }
//         }
//
//         stage('Run Docker Compose') {
//             steps {
//                 dir('conseil') {
//                     bat 'docker-compose up -d'
//                 }
//             }
//         }
//     }
//
//     post {
//         always {
//             cleanWs()
//         }
//         success {
//             echo 'Pipeline completed successfully!'
//         }
//         failure {
//             echo 'Pipeline failed!'
//         }
//     }
// }