pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker-credentials-id')
        SONARQUBE_TOKEN = 'squ_f31ef19109657ffbdfe45bd7307ae4f50992b20f'
        SONARQUBE_SERVER = 'http://localhost:9000'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Hamim-Hajar/Fil-Rouge-Conseil-Beauty.git'
            }
        }

        stage('Build & Test filRouge') {
            steps {
                dir('conseil') {
                    withMaven(maven: 'mvn') {
                        bat 'mvn clean install'
                    }
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarQubeScanner'
                    dir('conseil') {
                        bat "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=conseil -Dsonar.sources=. -Dsonar.host.url=${SONARQUBE_SERVER} -Dsonar.login=${SONARQUBE_TOKEN} -Dsonar.java.binaries=target/classes"
                    }
                }
            }
        }

        stage('Build Docker Image & Push') {
            steps {
                dir('conseil') {
                    script {
                        try {
                            bat 'docker context use default'

                            def imageTag = env.TAG_VERSION ?: 'latest'
                            def dockerImage = docker.build("hajarhamim/fil-rouge-conseil:${imageTag}")

                            docker.withRegistry('https://index.docker.io/v1/', 'docker-credentials-id') {
                                dockerImage.push()
                            }
                        } catch (Exception e) {
                            error "Docker build or push failed: ${e.message}"
                        }
                    }
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                dir('conseil') {
                    bat 'docker-compose up -d'
                }
            }
        }
    }
}